### PR TITLE
Add read/write roundtrip test

### PR DESCRIPTION
**Pull request by hannahilea**
- Add basic read/write roundtrip test case (in service of #30)
- Define `Base.==` and `Base.isequal` for `AbstractSpdx` types
- Bump patch version

In the future, given the addition of `Base.isequal`, most/all `compare` and `compare_b` functions could be removed, and `isequal` can be called instead.

### CODE REVIEW

**Comment by hannahilea** [comment]
This pulls codecov up to ~75%!

**Comment by SamuraiAku** [comment]
The new `==` function isn't working for me, but `isequal` does

```julia
julia> mysbom= readspdx("/Users/simon/.julia/dev/SPDX/SPDX.spdx.json");
julia> mysbom2= readspdx("/Users/simon/.julia/dev/SPDX/SPDX.spdx.json");
julia> mysbom == mysbom2  # What's missing?
missing
julia> isequal(mysbom, mysbom2)
true
julia> SPDX.compare(mysbom, mysbom2)
(bval = true, mismatches = Symbol[])
```

Then I make a modification to mysbom2 to test it
```julia
julia> mysbom2.Packages[2].LicenseInfoFromFiles
1-element Vector{Union{SpdxComplexLicenseExpressionV2, SpdxSimpleLicenseExpressionV2}}:
 NOASSERTION

julia> push!(mysbom2.Packages[2].LicenseInfoFromFiles, SpdxLicenseExpressionV2("MIT"))
2-element Vector{Union{SpdxComplexLicenseExpressionV2, SpdxSimpleLicenseExpressionV2}}:
 NOASSERTION
 MIT

julia> mysbom == mysbom2  # This is surprising
false
julia> isequal(mysbom, mysbom2)
false

julia> SPDX.compare(mysbom, mysbom2)
(bval = false, mismatches = [:Packages])
julia> SPDX.compare(mysbom.Packages, mysbom2.Packages)
You are comparing 2 vectors. Use broadcast "compare.(...)" to compare their contents
(bval = false, mismatches = Symbol[])
julia> SPDX.compare.(mysbom.Packages, mysbom2.Packages)
26-element Vector{NamedTuple{(:bval, :mismatches), Tuple{Bool, Vector{Symbol}}}}:
 (bval = 1, mismatches = [])
 (bval = 0, mismatches = [:LicenseInfoFromFiles])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 ⋮
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
 (bval = 1, mismatches = [])
```

I don't understand why `==` returns `false` when the sboms don't match but `missing` when they do.

I'm surprised these functions were able to correctly detect that the modified sbom was different.  I added a value to a vector within a structure within a vector in the sbom.  Wasn't sure that the comparison would go all the way down.

Also, quick note from the documentation
```julia
help?> isequal
.....
  Implementation
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  The default implementation of isequal calls ==, so a type that does not involve floating-point values generally only
  needs to define ==.
......
```

**Comment by SamuraiAku** [comment]
I believe that the cause of the `==` returning `missing` is because there are many fields throughout the document with the value of `missing`.  This was a deliberate design choice to make it clear which fields have not been set by the user.  The the examples above the following fields are set like this:

```
mysbom.CreationInfo.LicenseListVersion
mysbom.Packages[1].ReleaseDate
```

And `==` is defined as [returning three-valued logic](https://docs.julialang.org/en/v1/base/math/#Base.:==) so I guess everything is working as intended here.

The tests are using `isequal` so there doesn't appear to be any issues to worry about.

**Comment by SamuraiAku** [comment]
@hannahilea can you move the definitions of `==` and `isequal` from types.jl to analysis.jl?  That's where I defined `compare` and `compare_b`.  It's a better home for these methods.

Thanks.

**Comment by hannahilea** [comment]
Moved! I also included your tests directly, to demonstrate behavior.

> I'm surprised these functions were able to correctly detect that the modified sbom was different. I added a value to a vector within a structure within a vector in the sbom. Wasn't sure that the comparison would go all the way down.

Yeah, pretty cool, right? :) The function added in this PR iterates through all the fields of the `AbstractSpdx` type and calls `isequal` (or `==`) on each field. Since many of the fields of the `SBOM` you tested are themselves `<:AbstractSpdx`s, this new function is then applied recursively to them, as well, and so on.

**Comment by SamuraiAku** [comment]
Hooray for the Julia type system!

**Pull request merged**
